NUM_YEARS = 12
NUM_TRAINING_YEARS = 10
NUM_TEST_PERIODS=24

TRAINING_MONTHS = 1:(NUM_TRAINING_YEARS * 12)
TEST_MONTHS = (NUM_TRAINING_YEARS * 12+1):(NUM_YEARS*12)

LAST_TRAINING_MONTH = (NUM_TRAINING_YEARS * 12)
